### ISSUE TITLE
Setup coverage and threshold files to establish quality expectations and CodeCov integration

### ISSUE THREAD

**Issue by chambridge** [SaltCellar/SaltCellar#31]
As a developer, I want collect the code coverage of unit tests and set a reasonable threshold so that code added to the project has associated test cases as new features are introduced; coverage should be checked for every pull request using CodeCov.

## Acceptance Criteria

- [x] Verify that coverage is gathered based on the settings of the coverage file
- [x] Verify third party integration with CodeCov
- [x] Verify that coverage must meet a threshold defined in ._codecov.yml_

**Comment by chambridge** [comment]
I was expecting a `.coveragerc` file to be added as well.
Can we add a target into `tox.ini` and the `Makefile` to run test with coverage?

Expected to have CodeCov comments in the PRs after this is in master.

**Comment by blentz** [comment]
Finished the rest of the expected work in #48
