### ISSUE TITLE
Setup auto-documentation of code modules with Sphinx

### ISSUE THREAD

**Issue by chambridge** [SaltCellar/SaltCellar#38]
As a developer, I want documentation of the code within the project to be automated so that we can document as we code to provide information.

## Acceptance Criteria

- [x] Verify that the developed modules have associated documentation viewable within Read the docs.

**Comment by blentz** [comment]
the autodoc module was enabled when sphinx was configured. (PR #28)

**Comment by chambridge** [comment]
I get that the Sphinx module is enabled, but when you run build the docs there isn't any information about our code available. Just the initial Sphinx docs.

For example this is what the previous test team did and their output:
http://camayoc.readthedocs.io/en/latest/

**Comment by blentz** [comment]
Ok. I'll look at it more closely.

**Comment by aljesusg** [comment]
A suggestion.

Why no use travis to generate docs and deploy them in github-pages? 

Here is an example in the library that I am working https://github.com/open-charade/chargeback and you can see the results in https://open-charade.github.io/chargeback/

**Comment by adberglund** [comment]
Docs at https://saltcellar.readthedocs.io/en/latest/
