### ISSUE TITLE
Create swagger.yml file to document our API (use OpenAPI v3)

### ISSUE THREAD

**Issue by chambridge** [SaltCellar/SaltCellar#40]
As a developer, I want to be able to share our API via Swagger so that it can be consumed by other customer or they can generate client code using the defined API.

We plan on sharing/composing APIs across services using the Open API definition

## Acceptance Criteria

- [ ] Verify that a basic swagger.yml file exist describing the current API

**Comment by adberglund** [comment]
If we use Django Rest Framework for our APIs then `drf-yasg` [drf-yasg docs](https://drf-yasg.readthedocs.io/en/stable/) is easy to setup to auto-generate swagger. It can be used to spit out JSON and YAML for Swagger or optionally expose both `/swagger/` and `/redoc/` UIs to test/consume the APIs from.

**Comment by chambridge** [comment]
Looks like [drf-yasg doesn't yet support OpenAPI 3](https://github.com/axnsan12/drf-yasg/issues/33).
